Repository nairnairnair/nunslinger, pull requests merged in 2022-09, with the labels that each got.

#4 Add background, placeholder model and placeholder song
  public/Assets/Backgrounds/cathedral.jpeg
  public/Assets/Models/nun-gun-isolated-white-59019688.jpeg
  public/Assets/Music/Nun_Moment_2.mov
Labels: enhancement

#7 Add Missions class and related CSS stylings, refactor App to accommodate
  src/component/App/App.tsx
  src/component/Battleground/Battleground.tsx
  src/component/Characters/CharacterCard.tsx
  src/component/Game/Game.tsx
  src/component/Missions/Missions.css
  src/component/Missions/Missions.tsx
Labels: enhancement

#10 basic set up for styling, api call, and cypress
  cypress.config.ts
  cypress/e2e/spec.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package.json
  src/Assets/Backgrounds/battlePage.jpeg
  src/Assets/Backgrounds/confess.jpeg
  src/Assets/Fonts/angelWish.otf
  src/Assets/Fonts/angelWish.ttf
  src/Assets/Fonts/fonts.d.ts
  src/component/App/App.css
  src/component/App/App.test.tsx
  src/component/App/App.tsx
  src/component/Game/Game.css
  src/component/Game/Game.tsx
  src/component/Missions/Missions.css
  src/component/Missions/Missions.tsx
  src/component/fetch/fetchApiData.tsx
  src/index.tsx
Labels: enhancement

#11 set up music in game component
  src/component/App/App.tsx
  src/component/Game/Game.tsx
  src/component/HealthBar/HealthBar.css
  src/component/HealthBar/HealthBar.tsx
Labels: enhancement

#13 Add file containing object of dialogue cutscene arrays
  src/component/Missions/MissionCutscenes.tsx.tsx
Labels: enhancement

#16 Refactored some hooks in place of class-based components and added ch…
  src/Assets/Models/Demon-Leaving-2.png
  src/component/App/App.tsx
  src/component/Characters/Enemy.css
  src/component/Characters/Enemy.tsx
  src/component/Characters/Player.css
  src/component/Characters/Player.tsx
  src/component/Game/Game.css
  src/component/Game/Game.tsx
  src/component/HealthBar/EnemyHealthBar.tsx
  src/component/HealthBar/PlayerHealthBar.tsx
  src/component/Missions/Missions.css
  src/component/fetch/fetchApiData.tsx
  src/index.tsx
Labels: bug, enhancement

#20 Add enemy models object and interface, add placeholder for studio name on title screen
  src/component/App/App.tsx
  src/component/Characters/Enemy.tsx
Labels: enhancement

#21 Add enemyShoot, capturePlayerShot, compareShots, shotSecondHitCheck functions and relevant pieces of state
  src/component/Game/Game.tsx
Labels: enhancement

#22 set up health bar changing methods
  src/component/Game/Game.tsx
  src/component/HealthBar/HealthBar.css
Labels: enhancement

#23 setup trigger button
  src/component/Characters/Enemy.tsx
  src/component/Characters/character.ts
  src/component/Game/Game.css
  src/component/Game/Game.tsx
Labels: enhancement

#25 Add game over check, add round looping functionality, refactor hit checks and shot order handling, basic game functionality complete
  src/component/Game/Game.tsx
Labels: enhancement

#28 complete toggling between languages
  src/component/App/App.tsx
  src/component/Game/Game.tsx
  src/component/Missions/Missions.tsx
  src/component/fetch/fetchApiData.tsx
Labels: enhancement

#32 redo toggle
  src/component/App/App.tsx
  src/component/Game/Game.tsx
Labels: documentation, enhancement

#35 Add Patrick's animation fixes, refactor game logic to not show next l…
  src/component/Characters/Enemy.tsx
  src/component/Characters/Player.tsx
  src/component/Game/Game.css
  src/component/Game/Game.tsx
Labels: bug

#42 Add more tests for cypress
  cypress/e2e/game.cy.ts
  src/component/Game/Game.css
  src/component/Game/Game.tsx
Labels: enhancement

#43 start readme
  README.md
Labels: documentation

#45 refactor game
  cypress/e2e/missions.cy.ts
  src/component/Game/Game.css
  src/component/Game/Game.tsx
Labels: enhancement

#50 finish testing
  cypress/e2e/game.cy.ts
  cypress/e2e/homePage.cy.ts
  cypress/e2e/mainPages.cy.ts
  src/component/App/App.tsx
Labels: enhancement

#54 final refactor
  src/component/Game/Game.tsx
Labels: bug
